language: C

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev libglib2.0-dev intltool gtk-doc-tools libusb-1.0-0-dev libaudit-dev libpcap-dev libgstreamer-plugins-base1.0-dev libgtk-3-dev libnotify-dev

before_script: ./autogen.sh

script:
  - ./configure --disable-usb --disable-viewer --disable-packet-socket --disable-gst-plugin --disable-cpp-test && make clean && make && make test
  - ./configure --enable-usb --enable-viewer --enable-packet-socket --enable-gst-plugin --disable-cpp-test && make clean && make && make test
