os:
  - linux
  - osx

dist: xenial

matrix:
  allow_failures:
    - os: osx

addons:
  apt:
    packages:
      - libxml2-dev
      - libglib2.0-dev
      - intltool
      - gtk-doc-tools
      - libusb-1.0-0-dev
      - libaudit-dev
      - ninja-build
      - python3-pip
      - python3-dev
      - gobject-introspection
    update: true

language: C

compiler:
  - clang
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ninja intltool; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force gettext ; fi
  - sudo pip3 install --upgrade pip
  - sudo pip3 install setuptools
  - sudo pip3 install 'meson==0.47'

script:
  - meson build -Dintrospection=false -Dviewer=false -Dgst-plugin=false -Ddocumentation=false
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then meson configure -Dpacket-socket=false ; fi
  - meson configure
  - ninja
  - ninja test
